name: Release Creator

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - uses: alice-biometrics/release-creator/@v1.0.4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: 'v0.0.9.9.21-beta'
          description: '* Debugging'
          repo: 'jmutnick/hourly-forecast'  
          branch: 'master'
          draft: 'false'
          prerelease: 'false'
